export const jerseySampleAPI = [
  {
    type: "plain",
    base: "e10000",
    sleeve: "ffffff",
    number: "ffffff",
    squares: false,
    stripes: false,
    horizontal_stripes: false,
    split: false,
    shirt_type: "short_sleeves",
    sleeve_detail: "000000",
  },
  {
    type: "split",
    base: "b4eff8",
    sleeve: "f6f5f5",
    sleeve_detail: "97f8f6",
    squares: false,
    stripes: false,
    horizontal_stripes: false,
    split: true,
    split_color: "f8f8f8",
    shirt_type: "short_sleeves",
    number: "ffffff",
  },
  {
    type: "horizontal_stripes",
    base: "ffffff",
    sleeve: "ffffff",
    sleeve_detail: "eb2f3d",
    squares: false,
    stripes: false,
    horizontal_stripes: true,
    horizontal_stripes_color: "005dab",
    split: false,
    shirt_type: "short_sleeves",
    number: "ffffff",
  },
  {
    type: "stripes",
    base: "1017da",
    sleeve: "1017da",
    sleeve_detail: "1017da",
    squares: false,
    stripes: true,
    stripes_color: "b32919",
    horizontal_stripes: false,
    split: false,
    shirt_type: "short_sleeves",
    number: "000000",
  },
  {
    type: "squares",
    base: "cb0b1e",
    sleeve: "cb0b1e",
    sleeve_detail: "ffffff",
    squares: true,
    squares_color: "ffffff",
    stripes: false,
    horizontal_stripes: false,
    split: false,
    shirt_type: "short_sleeves",
    number: "000000",
  },
];

export const jerseyAPI = [
  {
    team: "Arsenal",
    jerseys: [
      {
        type: "home",
        base: "e10000",
        sleeve: "ffffff",
        number: "ffffff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "000000",
      },
      {
        type: "away",
        base: "e8e86d",
        sleeve: "e8e86d",
        number: "000352",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "f90101",
      },
      {
        type: "third",
        base: "f2f3f5",
        sleeve: "f0f2f5",
        number: "111010",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "0a244d",
      },
    ],
  },
  {
    team: "Augsburg",
    jerseys: [
      {
        type: "home",
        base: "ff0000",
        sleeve: "ff0000",
        number: "ffffff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "ff0000",
      },
      {
        type: "away",
        base: "dedede",
        sleeve: "dedede",
        number: "ff0000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "dedede",
      },
      {
        type: "third",
        base: "000000",
        sleeve: "000000",
        number: "ff0000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        sleeve_detail: "000000",
      },
    ],
  },
  {
    team: "Brentford",
    jerseys: [
      {
        type: "home",
        base: "ff0000",
        sleeve: "ff0000",
        sleeve_detail: "ff0000",
        squares: false,
        stripes: true,
        stripes_color: "fafafa",
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "away",
        base: "303030",
        sleeve: "575757",
        sleeve_detail: "575757",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
      {
        type: "third",
        base: "f0e928",
        sleeve: "ffffff",
        sleeve_detail: "f0e928",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
    ],
  },
  {
    team: "Bayer Leverkusen",
    jerseys: [
      {
        type: "home",
        base: "000000",
        sleeve: "000000",
        sleeve_detail: "000000",
        squares: false,
        stripes: true,
        stripes_color: "ffffff",
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
      {
        type: "away",
        base: "ffffff",
        sleeve: "ffffff",
        sleeve_detail: "ffffff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "third",
        base: "0e07c5",
        sleeve: "ffffff",
        sleeve_detail: "ffffff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
    ],
  },
  {
    team: "Crystal Palace",
    jerseys: [
      {
        type: "home",
        base: "1017da",
        sleeve: "1017da",
        sleeve_detail: "1017da",
        squares: false,
        stripes: true,
        stripes_color: "b32919",
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "away",
        base: "f8f7f7",
        sleeve: "ffffff",
        sleeve_detail: "fbf9f9",
        squares: false,
        stripes: true,
        stripes_color: "ec0404",
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
      {
        type: "third",
        base: "b4eff8",
        sleeve: "f6f5f5",
        sleeve_detail: "97f8f6",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: true,
        split_color: "f8f8f8",
        shirt_type: "short_sleeves",
        number: "000000",
      },
    ],
  },
  {
    team: "Dortmund",
    jerseys: [
      {
        type: "home",
        base: "fdea02",
        sleeve: "000000",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "away",
        base: "000000",
        sleeve: "000000",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffee00",
      },
      {
        type: "third",
        base: "ffffff",
        sleeve: "ffffff",
        sleeve_detail: "00b35c",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "00b35c",
      },
    ],
  },
  {
    team: "New Castle",
    jerseys: [
      {
        type: "home",
        base: "000000",
        sleeve: "000000",
        sleeve_detail: "1017da",
        squares: false,
        stripes: true,
        stripes_color: "ffffff",
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ff0000",
      },
      {
        type: "away",
        base: "2c2c2d",
        sleeve: "2e2c2d",
        sleeve_detail: "2e2c2d",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "d3ba79",
      },
      {
        type: "third",
        base: "116efa",
        sleeve: "0d42db",
        sleeve_detail: "050505",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "fcfcfc",
      },
    ],
  },
  {
    team: "Hertha Berlin",
    jerseys: [
      {
        type: "home",
        base: "ffffff",
        sleeve: "ffffff",
        sleeve_detail: "004cff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "0059ff",
      },
      {
        type: "away",
        base: "01033c",
        sleeve: "01033c",
        sleeve_detail: "001fb8",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "00ccff",
      },
      {
        type: "third",
        base: "2c0af5",
        sleeve: "2c0af5",
        sleeve_detail: "18191b",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
    ],
  },
  {
    team: "Tottenham",
    jerseys: [
      {
        type: "home",
        base: "ffffff",
        sleeve: "ffffff",
        sleeve_detail: "ffffff",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "away",
        base: "3b3a4d",
        sleeve: "3b3a4d",
        sleeve_detail: "242426",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "third",
        base: "c76ed8",
        sleeve: "ffffff",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
    ],
  },
  {
    team: "Mainz",
    jerseys: [
      {
        type: "home",
        base: "c76ed8",
        sleeve: "ffffff",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "000000",
      },
      {
        type: "away",
        base: "000000",
        sleeve: "000000",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "989966",
      },
      {
        type: "third",
        base: "faf9f6",
        sleeve: "faf9f6",
        sleeve_detail: "faf9f6",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ff0000",
      },
    ],
  },
  {
    team: "Watford",
    jerseys: [
      {
        type: "home",
        base: "fff000",
        sleeve: "fff000",
        sleeve_detail: "242321",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "242321",
      },
      {
        type: "away",
        base: "b91516",
        sleeve: "b91516",
        sleeve_detail: "b91516",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
      {
        type: "third",
        base: "3a645f",
        sleeve: "3a645f",
        sleeve_detail: "ccc500",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ccc500",
      },
    ],
  },
  {
    team: "RB Leizpig",
    jerseys: [
      {
        type: "home",
        base: "ffffff",
        sleeve: "ff0000",
        sleeve_detail: "ff0000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ff0000",
      },
      {
        type: "away",
        base: "000000",
        sleeve: "000000",
        sleeve_detail: "000000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
      {
        type: "third",
        base: "ff0000",
        sleeve: "ff0000",
        sleeve_detail: "ff0000",
        squares: false,
        stripes: false,
        horizontal_stripes: false,
        split: false,
        shirt_type: "short_sleeves",
        number: "ffffff",
      },
    ],
  },
];
